Inject CSRF token into template to make it work with CSRF_COOKIE_HTTPONLY
YPlan/nexus pull request #92
Opened 2017-01-17 10:08 UTC by Duologic

Discussion in issue: https://github.com/YPlan/nexus/issues/90

2017-01-17 10:09 UTC, graingert requested changes

2017-01-17 10:09 UTC, graingert commented on nexus/media/js/nexus.js
> +            var csrf_token = $('#nexus-constants').data('csrfToken');
csrfToken

2017-01-17 10:09 UTC, graingert commented on nexus/media/js/nexus.js
> +            var csrf_token = $('#nexus-constants').data('csrfToken');
or CSRFToken

2017-01-17 10:11 UTC, graingert requested changes

2017-01-17 10:11 UTC, graingert commented on nexus/templates/nexus/base.html
> +                data-csrf-token="{{ csrf_token }}"
tbh, I'd probably go for data-nexus-csrf-token

2017-01-17 10:14 UTC, Duologic commented on nexus/templates/nexus/base.html
> +                data-csrf-token="{{ csrf_token }}"
Sounds sane, I'll keep it open for now.

2017-01-17 10:15 UTC, graingert commented
@Duologic also update the HISTORY.rst

2017-01-17 10:16 UTC, graingert commented
Commit message: SSL -> TLS, although it's redundant here HTTPOnly is what matters.
Add a `Fixes: #90` somewhere.

2017-01-17 10:17 UTC, Duologic commented
I'll squash the changes into one commit

2017-01-17 10:20 UTC, Duologic commented
Thanks for the review!

2017-01-17 10:24 UTC, adamchainz requested changes

2017-01-17 10:24 UTC, adamchainz commented on nexus/templates/nexus/base.html
> +                data-csrf-token="{{ csrf_token }}"
no need for 'nexus' in name imo, the nexus in nexus-media-prefix was pre-existing for the `nexus_media_prefix` tag

2017-01-17 10:24 UTC, adamchainz commented on nexus/templatetags/nexus_helpers.py
> -def nexus_csrf_cookie_name():
I'd document the removal of this in HISTORY.rst just in case someone has used it in their own templates

2017-01-17 10:29 UTC, Duologic commented on nexus/templatetags/nexus_helpers.py
> -def nexus_csrf_cookie_name():
Done.

2017-01-17 10:30 UTC, Duologic commented
Should I change the version in `nexus/__init__.py` or does that happen in the merge?

2017-01-17 10:32 UTC, adamchainz commented
That happens in release commits only

2017-01-17 14:35 UTC, Duologic commented
Alright, I think I got everything.

How do we go from here? Do you guys have release cycle of some kind?

2017-01-17 14:41 UTC, adamchainz commented
I'll merge and release tonight

2017-01-19 08:06 UTC, Duologic commented
Long days you have there... :P

2017-01-19 08:51 UTC, adamchainz commented
Yes I'm on Venus

2017-01-19 08:52 UTC, adamchainz approved these changes

2017-01-19 08:57 UTC, adamchainz commented
Merged in 73375ec0ede7315049c16cdce6bfdd9ed32cd19b, thanks!

2017-01-19 08:57 UTC, closed without merging

2017-01-19 09:09 UTC, adamchainz commented
V1.5.0 on PyPI now: https://pypi.python.org/pypi/nexus-yplan

2017-01-20 13:27 UTC, Duologic commented
Closing the feedback loop here, this is now in production for us and working terrific. Thanks for maintaining the nexus and gargoyle packages!